name: 📜 RFC Proposal
description: Submit a Request for Comments for significant protocol changes
title: "[RFC]: "
labels: ["rfc", "proposal", "discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## RFC Process
        
        RFCs are for **significant changes** to the ACP protocol. This includes:
        - New annotation namespaces or major syntax changes
        - New constraint types or behavioral changes
        - Breaking changes to file formats
        - Major new features affecting multiple components
        
        For smaller changes, please use a [Feature Request](./feature_request.yml) instead.
        
        ### RFC Lifecycle
        1. **Draft** → Initial submission (this form)
        2. **Proposed** → Formal review begins
        3. **Final Comment Period** → 10 days for final feedback
        4. **Accepted/Rejected** → Decision made
        
        ---

  - type: input
    id: title
    attributes:
      label: RFC Title
      description: A short, descriptive title for this RFC
      placeholder: "e.g., Add Performance Annotations"
    validations:
      required: true

  - type: dropdown
    id: rfc-type
    attributes:
      label: RFC Type
      description: What type of change is this?
      options:
        - "Feature - New capability"
        - "Enhancement - Improve existing feature"
        - "Breaking - Incompatible change"
        - "Process - Development/governance change"
        - "Informational - Documentation or guidance"
    validations:
      required: true

  - type: dropdown
    id: components
    attributes:
      label: Affected Components
      description: Which components would this RFC affect?
      multiple: true
      options:
        - Specification (ACP-1.0.md)
        - Annotation Syntax
        - Constraint System
        - Variable System
        - Cache Format
        - Config Format
        - Query Interface
        - CLI
        - MCP Server
        - JSON Schemas
        - Multiple/All
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change Level
      description: What level of breaking change does this introduce?
      options:
        - "None - Fully backward compatible"
        - "Minor - Deprecates existing features"
        - "Major - Requires migration"
        - "Critical - Fundamental protocol change"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One paragraph explanation of the proposal
      placeholder: This RFC proposes...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Why are we doing this? What use cases does it support? What problems does it solve?
      placeholder: |
        ### Problem
        Currently, ACP lacks...
        
        ### Impact
        This affects users who...
        
        ### Goals
        This RFC aims to...
    validations:
      required: true

  - type: textarea
    id: detailed-design
    attributes:
      label: Detailed Design
      description: |
        The bulk of the RFC. Explain the design in enough detail for someone familiar with ACP to understand and implement.
      placeholder: |
        ### Overview
        
        ### Syntax
        ```
        @acp:new-feature value
        ```
        
        ### Schema Changes
        ```json
        {
          "new_field": { "type": "string" }
        }
        ```
        
        ### Behavior
        
        ### Examples
    validations:
      required: true

  - type: textarea
    id: drawbacks
    attributes:
      label: Drawbacks
      description: Why should we *not* do this? Be honest about the downsides.
      placeholder: |
        - Increases complexity because...
        - May confuse users who...
        - Implementation cost is...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What other designs were considered? What is the impact of not doing this?
      placeholder: |
        ### Alternative A
        Description... Rejected because...
        
        ### Alternative B
        Description... Rejected because...
        
        ### Do Nothing
        Impact of not implementing this RFC...
    validations:
      required: true

  - type: textarea
    id: compatibility
    attributes:
      label: Compatibility
      description: How does this affect existing users and future development?
      placeholder: |
        ### Backward Compatibility
        Existing users will...
        
        ### Forward Compatibility
        Future ACP development will...
        
        ### Migration Path
        Users can migrate by...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Plan
      description: What changes are needed across the ecosystem?
      placeholder: |
        ### Specification Changes
        - Section X needs...
        
        ### Schema Changes
        - cache.schema.json: Add...
        
        ### CLI Changes
        - New command/flag...
        
        ### MCP Server Changes
        - New tool/resource...
        
        ### Documentation Changes
        - Update chapter...
    validations:
      required: true

  - type: textarea
    id: open-questions
    attributes:
      label: Open Questions
      description: List any unresolved questions that need community input
      placeholder: |
        1. Should we...?
        2. How should we handle...?
        3. Is X or Y preferred for...?
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related issues, RFCs, or external resources
      placeholder: |
        - Related issue: #123
        - Similar approach in X: [link]
        - Research paper: [link]
    validations:
      required: false

  - type: dropdown
    id: champion
    attributes:
      label: RFC Champion
      description: Are you willing to champion this RFC through the process?
      options:
        - "Yes - I will shepherd this RFC"
        - "Maybe - I need help"
        - "No - Seeking a champion"
    validations:
      required: true

  - type: dropdown
    id: implementation-commitment
    attributes:
      label: Implementation Commitment
      description: Are you willing to implement this if accepted?
      options:
        - "Yes - I will implement this"
        - "Partial - I can implement some parts"
        - "No - Implementation help needed"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: RFC Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing RFCs to ensure this hasn't been proposed
          required: true
        - label: This change is significant enough to warrant an RFC
          required: true
        - label: I have considered backward compatibility
          required: true
        - label: I have provided sufficient detail for implementation
          required: true
        - label: I am prepared to respond to feedback and iterate on this RFC
          required: true